#!/usr/bin/env python3
"""Victim-impact sanity checks (attacks per victim), by tier.

DEPRECATED / NOT USED IN THE PAPER: no .tex file in this repository reads
this script's output -- fig_victim_impact_metrics.tex uses hardcoded
coordinates transcribed from output/tables/table4_victim_tiers.csv
(verified to match it exactly), which is generated by src/m4_victims.py,
the methodologically correct and currently-maintained implementation.

This script previously also computed two fabricated figures that have
been removed entirely rather than fixed, since no real data exists in
this export to compute them from:
  - "absolute_loss" was avg_tx_size * 0.01, i.e. an invented, uncited flat
    1% per-attack loss assumption applied to every tier. This directly
    contradicts this project's own paper (see the Robustness/Limitations
    section of main.tex), which correctly states that realised victim
    loss requires trade-level slippage decomposition not available here.
  - "cumulative_loss_rate" was attacks_per_victim * 1.0 -- multiplying by
    exactly 1.0 is a no-op; this relabeled the attacks-per-victim count as
    a percentage "loss rate" without computing anything different.
It also previously read the legacy fetch/query5b_victim_impact.csv; it
now reads the current revised export instead (see the same schema-rename
note in calc_attack_intensity.py's docstring).
Kept only as a standalone sanity check against table4_victim_tiers.csv;
prefer that table for anything going into the paper.
"""

import csv

if __name__ == "__main__":
    with open('fetch/data/revised-24m/query5b_victim_impact_v2.csv', 'r') as f:
        reader = csv.DictReader(f)
        data = list(reader)

    # Attacks per victim-address-with-a-trade-in-tier: a real ratio of two
    # real columns, kept as a sanity check only. No loss/dollar figure is
    # computed here -- this export does not contain the trade-level
    # slippage data that would be required to compute a real one.
    for row in data:
        victim_trades = float(row['victim_trades'])
        addresses = float(row['addresses_with_trade_in_tier'])
        attacks_per_address = victim_trades / addresses
        print(f"{row['victim_tier']}: attacks_per_address={attacks_per_address:.4f} "
              f"(sanity check only -- see output/tables/table4_victim_tiers.csv for the published figure)")
